
# To perform ML by using  dimensionality reduction techniques PCA , TSNE (Unsuperwised learning)

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('/content/data.csv')

In [35]:
del df['PassengerId']
del df['Ticket']
del df['Fare']
del df['Cabin']
del df['Name']
df['Age'] = df['Age'].fillna(df['Age'].mean())

df = df.dropna()
df['Age'] = df['Age'].astype(int)
df = pd.get_dummies(df,columns= ['Sex','Embarked','Pclass'],drop_first=False,dtype=int)
df['No.of_peoples'] = df['Parch'] + df['SibSp']
del df['SibSp']
del df['Parch']
df['Age'] = df['Age']/df['Age'].max()
df['No.of_peoples'] = df['No.of_peoples']/df['No.of_peoples'].max()
y = df['Survived']
del df['Survived']
x = df

In [36]:
x

,Age,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3,No.of_peoples
0,0.2750,0,1,0,0,1,0,0,1,0.1
1,0.4750,1,0,1,0,0,1,0,0,0.1
2,0.3250,1,0,0,0,1,0,0,1,0.0
3,0.4375,1,0,0,0,1,1,0,0,0.1
4,0.4375,0,1,0,0,1,0,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...
886,0.3375,0,1,0,0,1,0,1,0,0.0
887,0.2375,1,0,0,0,1,1,0,0,0.0
888,0.3625,1,0,0,0,1,0,0,1,0.3
889,0.3250,0,1,1,0,0,1,0,0,0.0
890,0.4000,0,1,0,1,0,0,0,1,0.0

In [37]:
from sklearn.decomposition import PCA

n = 3
pca = PCA(n_components=n)
columns = ['pca_'+str(i+1) for i in range(n) ]
x_pca = pca.fit_transform(x)

x_pca_df = pd.DataFrame(x_pca , columns = columns)

x_pca_df

        pca_1     pca_2     pca_3
0   -0.755269  0.241246  0.081677
1    1.460202 -0.284500 -0.834429
2    0.441686  0.865384  0.443233
3    1.052085 -0.262758  0.334593
4   -0.756146  0.221700  0.075043
..        ...       ...       ...
884 -0.314794 -0.746014  0.593453
885  1.046604 -0.249273  0.335363
886  0.450983  0.876183  0.452412
887  0.256096 -0.909002 -1.200572
888 -0.537993  0.471150 -0.704323

[889 rows x 3 columns]

In [38]:
x_train = x_pca_df[:650]
x_test  = x_pca_df[650:]

y_train = y[:650]
y_test  = y[650:]

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(x_train,y_train)
print("Model trained successfully for PCA")

Model trained successfully for PCA

In [39]:
accuracy = model.score(x_train,y_train)
print(f"Training Accuracy of the Model: {round( accuracy*100 , 2 )} % " )



# Testing Accuracy
accuracy = model.score(x_test,y_test)
print(f"Testing Accuracy of the Model  : {round( accuracy*100 , 2 )} % " )

Training Accuracy of the Model: 78.62 %
Testing Accuracy of the Model  : 78.66 %

By using TSNE

In [40]:
from sklearn.manifold import TSNE
n = 3
tsne = TSNE(n_components=n)
columns = ['tsne_'+str(i+1) for i in range(n) ]
x_tsne = tsne.fit_transform(x)

x_tsne_df = pd.DataFrame(x_tsne , columns = columns)

x_pca_df

        pca_1     pca_2     pca_3
0   -0.755269  0.241246  0.081677
1    1.460202 -0.284500 -0.834429
2    0.441686  0.865384  0.443233
3    1.052085 -0.262758  0.334593
4   -0.756146  0.221700  0.075043
..        ...       ...       ...
884 -0.314794 -0.746014  0.593453
885  1.046604 -0.249273  0.335363
886  0.450983  0.876183  0.452412
887  0.256096 -0.909002 -1.200572
888 -0.537993  0.471150 -0.704323

[889 rows x 3 columns]

In [41]:
x_train = x_tsne_df[:650]
x_test  = x_tsne_df[650:]

y_train = y[:650]
y_test  = y[650:]

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(x_train,y_train)
print("Model trained successfully for TSNE")

Model trained successfully for TSNE

In [42]:
accuracy = model.score(x_train,y_train)
print(f"Training Accuracy of the Model: {round( accuracy*100 , 2 )} % " )



# Testing Accuracy
accuracy = model.score(x_test,y_test)
print(f"Testing Accuracy of the Model  : {round( accuracy*100 , 2 )} % " )

Training Accuracy of the Model: 79.54 %
Testing Accuracy of the Model  : 80.75 %

# A short note

Instead of feeding all features/dimensions/columns to the model we may want to represent the important information using fewer dimensions.


-- Whats PCA and why is it       supervised learning

PCA (Principal Component Analysis) is one of the most commonly used **techniques** for dimensionality reduction in Machine Learning .
PCA takes your original features and creates new features called Principal Components.

PCA doesn't need a target/label y instead it focuses on representing the features using fewer dimensions while retaining as much variance(variation) as possible